### ISSUE TITLE
issue with ForwardDiff

### ISSUE THREAD

**Issue by rveltz** [JuliaReach/ReachabilityBase.jl#18]
Hi,

Is this package complient with AD? I am using it through `Lazysets.jl` and I get the following error.

Thank you for your help

```julia
ERROR: MethodError: no method matching is_right_turn(::Vector{Float64}, ::StaticArraysCore.SVector{2, ForwardDiff.Dual{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Float64, 12}}, ::Vector{Float64})
Closest candidates are:
  is_right_turn(::AbstractVector{N}, ::AbstractVector{N}, ::AbstractVector{N}) where N<:Real at ~/.julia/packages/ReachabilityBase/VQJKD/src/Arrays/vector_operations.jl:312
  is_right_turn(::AbstractVector{N}, ::AbstractVector{N}) where N<:Real at ~/.julia/packages/ReachabilityBase/VQJKD/src/Arrays/vector_operations.jl:319
Stacktrace:
  [1] in(x::StaticArraysCore.SVector{2, ForwardDiff.Dual{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Float64, 12}}, P::LazySets.VPolygon{Float64, Vector{Float64}})
    @ LazySets ~/.julia/packages/LazySets/qS1SH/src/Sets/VPolygon.jl:448
```

**Comment by rveltz** [comment]
> I am not quite sure why it does not match the first candidate method.

Basically, you have [here](https://github.com/JuliaReach/ReachabilityBase.jl/blob/752cf4f41aba4d9e19e9d3b5616df90f32a83112/src/Arrays/vector_operations.jl#L312) the element eltype `N` which is enforced. 

About a MWE, I am not sure yet, it is from a big code. I would say that if you try something like 

```
ForwardDiff.jacobian( x -> x ∈ Polygon)
```
it should error

**Comment by schillic** [comment]
> Basically, you have [here](https://github.com/JuliaReach/ReachabilityBase.jl/blob/752cf4f41aba4d9e19e9d3b5616df90f32a83112/src/Arrays/vector_operations.jl#L312) the element eltype `N` which is enforced.

Okay, I misread the levels of curly braces in `StaticArraysCore.SVector{2, ForwardDiff.Dual{ForwardDiff.Tag{DiffEqBase.OrdinaryDiffEqTag, Float64}, Float64, 12}}`.

> About a MWE, I am not sure yet, it is from a big code. I would say that if you try something like
> 
> ```
> ForwardDiff.jacobian( x -> x ∈ Polygon)
> ```
> 
> it should error

Unfortunately no (I may be too inexperienced with the package, sorry).

```julia
julia> using LazySets, ForwardDiff

julia> Polygon = rand(VPolygon);  # not actually used yet

julia> ForwardDiff.jacobian( x -> x ∈ Polygon)
ERROR: MethodError: no method matching jacobian(::var"#5#6")
Closest candidates are:
  jacobian(::Any, ::StaticArraysCore.StaticArray) at ~/.julia/packages/ForwardDiff/pDtsf/src/jacobian.jl:85
  jacobian(::Any, ::AbstractArray, ::AbstractArray) at ~/.julia/packages/ForwardDiff/pDtsf/src/jacobian.jl:35
  jacobian(::Any, ::AbstractArray, ::AbstractArray, ::ForwardDiff.JacobianConfig{T}) where T at ~/.julia/packages/ForwardDiff/pDtsf/src/jacobian.jl:35
```

**Comment by schillic** [comment]
Alternatively you could try out the branch `schillic/18` in https://github.com/JuliaReach/ReachabilityBase.jl/pull/19. I think that should fix the problem.

**Comment by rveltz** [comment]
Ok I will try. I just réalise now that the mapping is non differentiable...
